/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: flex.skl,v 1.2 94/01/04 14:33:15 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN zz_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((zz_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE zzrestart( zzin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct zz_buffer_state *YY_BUFFER_STATE;

extern int zzleng;
extern FILE *zzin, *zzout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int zzwrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		zzless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the zzless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define zzless(n) \
	do \
		{ \
		/* Undo effects of setting up zztext. */ \
		*zz_cp = zz_hold_char; \
		zz_c_buf_p = zz_cp = zz_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up zztext again */ \
		} \
	while ( 0 )

#define unput(c) zzunput( c, zztext_ptr )


struct zz_buffer_state
	{
	FILE *zz_input_file;

	char *zz_ch_buf;		/* input buffer */
	char *zz_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int zz_buf_size;

	/* Number of characters read into zz_ch_buf, not including EOB
	 * characters.
	 */
	int zz_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int zz_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int zz_fill_buffer;

	/* Whether we've seen an EOF on this buffer. */
	int zz_eof_status;
#define EOF_NOT_SEEN 0
	/* "Pending" happens when the EOF has been seen but there's still
	 * some text to process.  Note that when we actually see the EOF,
	 * we switch the status back to "not seen" (via zzrestart()), so
	 * that the user can continue scanning by just pointing zzin at
	 * a new input file.
	 */
#define EOF_PENDING 1
	};

static YY_BUFFER_STATE zz_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER zz_current_buffer


/* zz_hold_char holds the character lost when zztext is formed. */
static char zz_hold_char;

static int zz_n_chars;		/* number of characters read into zz_ch_buf */


int zzleng;

/* Points to current character in buffer. */
static char *zz_c_buf_p = (char *) 0;
static int zz_init = 1;		/* whether we need to initialize */
static int zz_start = 0;	/* start state number */

/* Flag which is used to allow zzwrap()'s to do buffer switches
 * instead of setting up a fresh zzin.  A bit of a hack ...
 */
static int zz_did_buffer_switch_on_eof;

static void zzunput YY_PROTO(( int c, char *buf_ptr ));
void zzrestart YY_PROTO(( FILE *input_file ));
void zz_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void zz_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE zz_create_buffer YY_PROTO(( FILE *file, int size ));
void zz_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void zz_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int zz_start_stack_ptr = 0;
static int zz_start_stack_depth = 0;
static int *zz_start_stack = 0;
static void zz_push_state YY_PROTO(( int new_state ));
static void zz_pop_state YY_PROTO(( void ));
static int zz_top_state YY_PROTO(( void ));

#ifndef zztext_ptr
static void zz_flex_strcpy YY_PROTO(( char *, const char * ));
#endif

static void *zz_flex_alloc YY_PROTO(( unsigned int ));
static void *zz_flex_realloc YY_PROTO(( void *ptr, unsigned int ));
static void zz_flex_free YY_PROTO(( void * ));

#define zz_new_buffer zz_create_buffer

#define INITIAL 0
#define INCLUDE 1
#define COMMENT 2
#define QUOTED 3
typedef unsigned char YY_CHAR;
typedef int zz_state_type;
FILE *zzin = (FILE *) 0, *zzout = (FILE *) 0;
extern char *zztext;
#define zztext_ptr zztext

#ifdef __cplusplus
static int zzinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static zz_state_type zz_get_previous_state YY_PROTO(( void ));
static zz_state_type zz_try_NUL_trans YY_PROTO(( zz_state_type current_state ));
static int zz_get_next_buffer YY_PROTO(( void ));
static void zz_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up zztext.
 */
#define YY_DO_BEFORE_ACTION \
	zztext_ptr = zz_bp; \
	zzleng = zz_cp - zz_bp; \
	zz_hold_char = *zz_cp; \
	*zz_cp = '\0'; \
	zz_c_buf_p = zz_cp;

#define YY_END_OF_BUFFER 27
static const short int zz_accept[75] =
    {   0,
        0,    0,    0,    0,    0,    0,    7,    7,   27,   25,
       23,   20,   19,    3,   24,   19,   25,   18,   19,    2,
        1,   17,   16,   17,   21,   22,    8,   26,    7,    4,
        8,    8,    0,    0,   14,    0,    0,    2,    1,   15,
        7,    0,    6,    7,    0,    0,    0,    0,    9,    0,
        6,    5,    7,    0,    0,    0,    0,    0,    7,    0,
        0,    0,   10,    0,   12,    0,    0,    0,    0,    0,
        0,   11,   13,    0
    } ;

static const int zz_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,    5,   10,   11,
       11,    5,    5,   11,   12,   11,    5,   13,   13,   13,
       13,   13,   13,   13,   13,   14,   14,   11,   11,    5,
        5,    5,   11,    8,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       11,   16,   11,    5,   15,    8,   17,   15,   15,   15,

       18,   15,   19,   15,   20,   15,   15,   21,   22,   23,
       15,   24,   15,   25,   26,   27,   15,   15,   15,   15,
       28,   15,   29,    5,   30,   11,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int zz_meta[31] =
    {   0,
        1,    1,    1,    2,    2,    3,    2,    2,    1,    4,
        2,    2,    5,    5,    6,    7,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    2,    2
    } ;

static const short int zz_base[83] =
    {   0,
        0,    0,   28,   29,  138,  137,   38,   54,  139,  142,
      142,  142,  142,  142,  142,   21,  122,  142,   20,   22,
        0,  142,  142,  107,  142,  142,  142,  142,  120,  142,
        0,   36,   34,   25,  142,  125,   48,   51,    0,  142,
      118,   53,  117,   55,  109,  112,  105,  105,  142,   59,
      112,  142,   60,  108,  106,  103,  106,   64,  107,  104,
       95,  100,  142,  109,  142,   91,   94,   98,   91,   76,
       54,  142,  142,  142,   77,   84,   91,   97,  100,  105,
       61,  108
    } ;

static const short int zz_def[83] =
    {   0,
       74,    1,   75,   75,   76,   76,   77,   77,   74,   74,
       74,   74,   74,   74,   74,   74,   78,   74,   74,   74,
       79,   74,   74,   74,   74,   74,   74,   74,   80,   74,
       81,   80,   74,   74,   74,   74,   78,   74,   79,   74,
       80,   80,   82,   80,   74,   74,   74,   74,   74,   74,
       82,   74,   80,   74,   74,   74,   74,   74,   80,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,    0,   74,   74,   74,   74,   74,   74,
       74,   74
    } ;

static const short int zz_nxt[173] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   10,   16,   17,
       18,   19,   20,   20,   21,   10,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   18,   18,
       23,   23,   38,   38,   38,   38,   24,   24,   27,   27,
       28,   41,   47,   30,   41,   33,   31,   34,   44,   35,
       45,   46,   48,   32,   27,   27,   28,   36,   41,   30,
       50,   41,   31,   38,   38,   44,   43,   53,   49,   32,
       42,   58,   59,   49,   73,   42,   64,   22,   22,   22,
       22,   22,   22,   22,   25,   25,   25,   25,   25,   25,
       25,   29,   29,   29,   29,   29,   29,   29,   36,   36,

       72,   36,   36,   36,   39,   39,   41,   71,   41,   41,
       41,   41,   51,   51,   51,   70,   69,   68,   49,   67,
       66,   65,   42,   63,   62,   61,   60,   52,   57,   56,
       55,   54,   52,   42,   49,   42,   40,   37,   74,   26,
       26,    9,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74
    } ;

static const short int zz_chk[173] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,   19,   19,   20,   20,    3,    4,    7,    7,
        7,   32,   34,    7,   32,   16,    7,   16,   32,   16,
       33,   33,   34,    7,    8,    8,    8,   37,   42,    8,
       37,   42,    8,   38,   38,   42,   81,   44,   50,    8,
       44,   50,   53,   58,   71,   53,   58,   75,   75,   75,
       75,   75,   75,   75,   76,   76,   76,   76,   76,   76,
       76,   77,   77,   77,   77,   77,   77,   77,   78,   78,

       70,   78,   78,   78,   79,   79,   80,   69,   80,   80,
       80,   80,   82,   82,   82,   68,   67,   66,   64,   62,
       61,   60,   59,   57,   56,   55,   54,   51,   48,   47,
       46,   45,   43,   41,   36,   29,   24,   17,    9,    6,
        5,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74
    } ;

static zz_state_type zz_last_accepting_state;
static char *zz_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define zzmore() zzmore_used_but_not_detected
#define YY_MORE_ADJ 0
char *zztext;
# line 1 "../chop/cmd.lex"
# line 8 "../chop/cmd.lex"


#ifdef FLEX_SCANNER
#define YY_USER_INIT { zzin = mdfile; }
#else
static	char bf[1024];
static char *strptr = bf;
#undef input
#undef unput
#define unput(c)  ( *--strptr = c )
static input() {
	if (*strptr == 0) {
	    if (!fgets(bf + 200, sizeof(bf) - 200, mdfile)) return 0;
	    strptr = bf + 200;
	    }

	return *strptr++;
	}
zzwrap() {
    return 1;
    }
#endif


/* SUPPRESS 17 */
/* SUPPRESS 20 */
extern char *deback();

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( zztext, zzleng, 1, zzout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( zz_current_buffer->zz_is_interactive ) \
		{ \
		int c = getc( zzin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, zzin )) == 0) \
		  && ferror( zzin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "zzterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef zzterminate
#define zzterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) zz_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int zzlex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after zztext and zzleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register zz_state_type zz_current_state;
	register char *zz_cp, *zz_bp;
	register int zz_act;

# line 36 "../chop/cmd.lex"



	if ( zz_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! zz_start )
			zz_start = 1;	/* first start state */

		if ( ! zzin )
			zzin = stdin;

		if ( ! zzout )
			zzout = stdout;

		if ( zz_current_buffer )
			zz_init_buffer( zz_current_buffer, zzin );
		else
			zz_current_buffer =
				zz_create_buffer( zzin, YY_BUF_SIZE );

		zz_load_buffer_state();

		zz_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		zz_cp = zz_c_buf_p;

		/* Support of zztext. */
		*zz_cp = zz_hold_char;

		/* zz_bp points to the position in zz_ch_buf of the start of
		 * the current run.
		 */
		zz_bp = zz_cp;

		zz_current_state = zz_start;
zz_match:
		do
			{
			register YY_CHAR zz_c = zz_ec[YY_SC_TO_UI(*zz_cp)];
			if ( zz_accept[zz_current_state] )
				{
				zz_last_accepting_state = zz_current_state;
				zz_last_accepting_cpos = zz_cp;
				}
			while ( zz_chk[zz_base[zz_current_state] + zz_c] != zz_current_state )
				{
				zz_current_state = (int) zz_def[zz_current_state];
				if ( zz_current_state >= 75 )
					zz_c = zz_meta[(unsigned int) zz_c];
				}
			zz_current_state = zz_nxt[zz_base[zz_current_state] + (unsigned int) zz_c];
			++zz_cp;
			}
		while ( zz_base[zz_current_state] != 142 );

zz_find_action:
		zz_act = zz_accept[zz_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( zz_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*zz_cp = zz_hold_char;
			zz_cp = zz_last_accepting_cpos;
			zz_current_state = zz_last_accepting_state;
			goto zz_find_action;

case 1:
YY_USER_ACTION
# line 38 "../chop/cmd.lex"
{
			zzlval.text = string(zztext);
			return Identifier;
			}
	YY_BREAK
case 2:
YY_USER_ACTION
# line 43 "../chop/cmd.lex"
{
			zzlval.text = string(zztext);
			return Integer;
			}
	YY_BREAK
case 3:
YY_USER_ACTION
# line 48 "../chop/cmd.lex"
{
			BEGIN QUOTED;
			return Openquote;
			}
	YY_BREAK
case 4:
YY_USER_ACTION
# line 53 "../chop/cmd.lex"
{
			BEGIN INITIAL;
			return Closequote;
			}
	YY_BREAK
case 5:
YY_USER_ACTION
# line 58 "../chop/cmd.lex"
{
			/* A backslash that terminates an identifier in quoted
			 * mode is discarded.  For example "%add%l\t" becomes
			 * the identifiers %add, %l, followed by literal "t".
			 */
			zztext[strlen(zztext) - 1] = 0;
			zzlval.text = string(zztext+1);
			return Identifier;
			}
	YY_BREAK
case 6:
YY_USER_ACTION
# line 68 "../chop/cmd.lex"
{
			zzlval.text = string(zztext+1);
			return Identifier;
			}
	YY_BREAK
case 7:
YY_USER_ACTION
# line 73 "../chop/cmd.lex"
{
			zzlval.text = string(deback(zztext));
			return String;
			}
	YY_BREAK
case 8:
YY_USER_ACTION
# line 78 "../chop/cmd.lex"
{
			zzerror("bad char in quoted string\n");
			}
	YY_BREAK
case 9:
YY_USER_ACTION
# line 82 "../chop/cmd.lex"
{
			zzlval.text = string(zztext);
			return Integer;
			}
	YY_BREAK
case 10:
YY_USER_ACTION
# line 88 "../chop/cmd.lex"
{
			return Type;
			}
	YY_BREAK
case 11:
YY_USER_ACTION
# line 92 "../chop/cmd.lex"
{
			return Register;
			}
	YY_BREAK
case 12:
YY_USER_ACTION
# line 96 "../chop/cmd.lex"
{
			return Range;
			}
	YY_BREAK
case 13:
YY_USER_ACTION
# line 100 "../chop/cmd.lex"
{
			return Term;
			}
	YY_BREAK
case 14:
YY_USER_ACTION
# line 104 "../chop/cmd.lex"
{
			BEGIN INCLUDE;
			}
	YY_BREAK
case 15:
YY_USER_ACTION
# line 108 "../chop/cmd.lex"
{
			BEGIN INITIAL;
			}
	YY_BREAK
case 16:
YY_USER_ACTION
# line 112 "../chop/cmd.lex"
{
			mdlineno++;
			return Included;
			}
	YY_BREAK
case 17:
YY_USER_ACTION
# line 117 "../chop/cmd.lex"
{
			return Included;
			}
	YY_BREAK
case 18:
YY_USER_ACTION
# line 123 "../chop/cmd.lex"
{
				return zztext[0];
				}
	YY_BREAK
case 19:
YY_USER_ACTION
# line 126 "../chop/cmd.lex"
{
				return zztext[0];
				}
	YY_BREAK
case 20:
YY_USER_ACTION
# line 129 "../chop/cmd.lex"
{
				mdlineno++;
				}
	YY_BREAK
case 21:
YY_USER_ACTION
# line 132 "../chop/cmd.lex"
;
	YY_BREAK
case 22:
YY_USER_ACTION
# line 133 "../chop/cmd.lex"
{
				mdlineno++;
				BEGIN INITIAL;
				}
	YY_BREAK
case 23:
YY_USER_ACTION
# line 137 "../chop/cmd.lex"
;
	YY_BREAK
case 24:
YY_USER_ACTION
# line 138 "../chop/cmd.lex"
{
				BEGIN COMMENT;
				}
	YY_BREAK
case 25:
YY_USER_ACTION
# line 141 "../chop/cmd.lex"
{
				zzerror("bad char in initial state\n");
			    	}
	YY_BREAK
case 26:
YY_USER_ACTION
# line 144 "../chop/cmd.lex"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INCLUDE):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(QUOTED):
	zzterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int zz_amount_of_matched_text = zz_cp - zztext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*zz_cp = zz_hold_char;

		if ( zz_current_buffer->zz_input_file != zzin )
			{
			/* This can happen if we scan a file, zzwrap() returns
			 * 1, and then later the user points zzin at a new
			 * file to resume scanning.  We have to assure
			 * consistency between zz_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input file.
			 */
			zz_current_buffer->zz_input_file = zzin;
			zz_n_chars = zz_current_buffer->zz_n_chars;
			}

		/* Note that here we test for zz_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since zz_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( zz_c_buf_p <= &zz_current_buffer->zz_ch_buf[zz_n_chars] )
			{ /* This was really a NUL. */
			zz_state_type zz_next_state;

			zz_c_buf_p = zztext_ptr + zz_amount_of_matched_text;

			zz_current_state = zz_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * zz_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			zz_next_state = zz_try_NUL_trans( zz_current_state );

			zz_bp = zztext_ptr + YY_MORE_ADJ;

			if ( zz_next_state )
				{
				/* Consume the NUL. */
				zz_cp = ++zz_c_buf_p;
				zz_current_state = zz_next_state;
				goto zz_match;
				}

			else
				{
				goto zz_find_action;
				}
			}

		else switch ( zz_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				zz_did_buffer_switch_on_eof = 0;

				if ( zzwrap() )
					{
					/* Note: because we've taken care in
					 * zz_get_next_buffer() to have set up
					 * zztext, we can now set up
					 * zz_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					zz_c_buf_p = zztext_ptr + YY_MORE_ADJ;

					zz_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! zz_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				zz_c_buf_p =
					zztext_ptr + zz_amount_of_matched_text;

				zz_current_state = zz_get_previous_state();

				zz_cp = zz_c_buf_p;
				zz_bp = zztext_ptr + YY_MORE_ADJ;
				goto zz_match;

			case EOB_ACT_LAST_MATCH:
				zz_c_buf_p =
				&zz_current_buffer->zz_ch_buf[zz_n_chars];

				zz_current_state = zz_get_previous_state();

				zz_cp = zz_c_buf_p;
				zz_bp = zztext_ptr + YY_MORE_ADJ;
				goto zz_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of zzlex */


/* zz_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int zz_get_next_buffer()
	{
	register char *dest = zz_current_buffer->zz_ch_buf;
	register char *source = zztext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( zz_c_buf_p > &zz_current_buffer->zz_ch_buf[zz_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( zz_current_buffer->zz_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( zz_c_buf_p - zztext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = zz_c_buf_p - zztext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( zz_current_buffer->zz_eof_status != EOF_NOT_SEEN )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		zz_n_chars = 0;

	else
		{
		int num_to_read =
			zz_current_buffer->zz_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = zz_current_buffer;

			int zz_c_buf_p_offset = zz_c_buf_p - b->zz_ch_buf;

			b->zz_buf_size *= 2;
			b->zz_ch_buf = (char *)
				zz_flex_realloc( (void *) b->zz_ch_buf,
						 b->zz_buf_size );

			if ( ! b->zz_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			zz_c_buf_p = &b->zz_ch_buf[zz_c_buf_p_offset];

			num_to_read = zz_current_buffer->zz_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&zz_current_buffer->zz_ch_buf[number_to_move]),
			zz_n_chars, num_to_read );
		}

	if ( zz_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			zzrestart( zzin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			zz_current_buffer->zz_eof_status = EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	zz_n_chars += number_to_move;
	zz_current_buffer->zz_ch_buf[zz_n_chars] = YY_END_OF_BUFFER_CHAR;
	zz_current_buffer->zz_ch_buf[zz_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* zztext begins at the second character in zz_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * zz_get_previous_state() will have with '^' rules active.
	 */

	zztext_ptr = &zz_current_buffer->zz_ch_buf[1];

	return ret_val;
	}


/* zz_get_previous_state - get the state just before the EOB char was reached */

static zz_state_type zz_get_previous_state()
	{
	register zz_state_type zz_current_state;
	register char *zz_cp;

	zz_current_state = zz_start;

	for ( zz_cp = zztext_ptr + YY_MORE_ADJ; zz_cp < zz_c_buf_p; ++zz_cp )
		{
		register YY_CHAR zz_c = (*zz_cp ? zz_ec[YY_SC_TO_UI(*zz_cp)] : 1);
		if ( zz_accept[zz_current_state] )
			{
			zz_last_accepting_state = zz_current_state;
			zz_last_accepting_cpos = zz_cp;
			}
		while ( zz_chk[zz_base[zz_current_state] + zz_c] != zz_current_state )
			{
			zz_current_state = (int) zz_def[zz_current_state];
			if ( zz_current_state >= 75 )
				zz_c = zz_meta[(unsigned int) zz_c];
			}
		zz_current_state = zz_nxt[zz_base[zz_current_state] + (unsigned int) zz_c];
		}

	return zz_current_state;
	}


/* zz_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = zz_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static zz_state_type zz_try_NUL_trans( zz_state_type zz_current_state )
#else
static zz_state_type zz_try_NUL_trans( zz_current_state )
zz_state_type zz_current_state;
#endif
	{
	register int zz_is_jam;
	register char *zz_cp = zz_c_buf_p;

	register YY_CHAR zz_c = 1;
	if ( zz_accept[zz_current_state] )
		{
		zz_last_accepting_state = zz_current_state;
		zz_last_accepting_cpos = zz_cp;
		}
	while ( zz_chk[zz_base[zz_current_state] + zz_c] != zz_current_state )
		{
		zz_current_state = (int) zz_def[zz_current_state];
		if ( zz_current_state >= 75 )
			zz_c = zz_meta[(unsigned int) zz_c];
		}
	zz_current_state = zz_nxt[zz_base[zz_current_state] + (unsigned int) zz_c];
	zz_is_jam = (zz_current_state == 74);

	return zz_is_jam ? 0 : zz_current_state;
	}


#ifdef YY_USE_PROTOS
static void zzunput( int c, register char *zz_bp )
#else
static void zzunput( c, zz_bp )
int c;
register char *zz_bp;
#endif
	{
	register char *zz_cp = zz_c_buf_p;

	/* undo effects of setting up zztext */
	*zz_cp = zz_hold_char;

	if ( zz_cp < zz_current_buffer->zz_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = zz_n_chars + 2;
		register char *dest = &zz_current_buffer->zz_ch_buf[
					zz_current_buffer->zz_buf_size + 2];
		register char *source =
				&zz_current_buffer->zz_ch_buf[number_to_move];

		while ( source > zz_current_buffer->zz_ch_buf )
			*--dest = *--source;

		zz_cp += dest - source;
		zz_bp += dest - source;
		zz_n_chars = zz_current_buffer->zz_buf_size;

		if ( zz_cp < zz_current_buffer->zz_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( zz_cp > zz_bp && zz_cp[-1] == '\n' )
		zz_cp[-2] = '\n';

	*--zz_cp = (char) c;


	/* Note: the formal parameter *must* be called "zz_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up zztext again */
	}


#ifdef __cplusplus
static int zzinput()
#else
static int input()
#endif
	{
	int c;

	*zz_c_buf_p = zz_hold_char;

	if ( *zz_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* zz_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( zz_c_buf_p < &zz_current_buffer->zz_ch_buf[zz_n_chars] )
			/* This was really a NUL. */
			*zz_c_buf_p = '\0';

		else
			{ /* need more input */
			zztext_ptr = zz_c_buf_p;
			++zz_c_buf_p;

			switch ( zz_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( zzwrap() )
						{
						zz_c_buf_p =
						zztext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return zzinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					zz_c_buf_p = zztext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in zzinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *zz_c_buf_p;
	*zz_c_buf_p = '\0';	/* preserve zztext */
	zz_hold_char = *++zz_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void zzrestart( FILE *input_file )
#else
void zzrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! zz_current_buffer )
		zz_current_buffer = zz_create_buffer( zzin, YY_BUF_SIZE );

	zz_init_buffer( zz_current_buffer, input_file );
	zz_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void zz_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void zz_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( zz_current_buffer == new_buffer )
		return;

	if ( zz_current_buffer )
		{
		/* Flush out information for old buffer. */
		*zz_c_buf_p = zz_hold_char;
		zz_current_buffer->zz_buf_pos = zz_c_buf_p;
		zz_current_buffer->zz_n_chars = zz_n_chars;
		}

	zz_current_buffer = new_buffer;
	zz_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (zzwrap()) processing, but the only time this flag
	 * is looked at is after zzwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	zz_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void zz_load_buffer_state( void )
#else
void zz_load_buffer_state()
#endif
	{
	zz_n_chars = zz_current_buffer->zz_n_chars;
	zztext_ptr = zz_c_buf_p = zz_current_buffer->zz_buf_pos;
	zzin = zz_current_buffer->zz_input_file;
	zz_hold_char = *zz_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE zz_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE zz_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) zz_flex_alloc( sizeof( struct zz_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in zz_create_buffer()" );

	b->zz_buf_size = size;

	/* zz_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->zz_ch_buf = (char *) zz_flex_alloc( b->zz_buf_size + 2 );

	if ( ! b->zz_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in zz_create_buffer()" );

	zz_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void zz_delete_buffer( YY_BUFFER_STATE b )
#else
void zz_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == zz_current_buffer )
		zz_current_buffer = (YY_BUFFER_STATE) 0;

	zz_flex_free( (void *) b->zz_ch_buf );
	zz_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void zz_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void zz_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->zz_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->zz_ch_buf[0] = '\n';
	b->zz_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->zz_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->zz_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->zz_buf_pos = &b->zz_ch_buf[1];

	b->zz_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->zz_fill_buffer = 1;

	b->zz_eof_status = EOF_NOT_SEEN;
	}


#ifdef YY_USE_PROTOS
static void zz_push_state( int new_state )
#else
static void zz_push_state( new_state )
int new_state;
#endif
	{
	if ( zz_start_stack_ptr >= zz_start_stack_depth )
		{
		int new_size;

		zz_start_stack_depth += YY_START_STACK_INCR;
		new_size = zz_start_stack_depth * sizeof( int );

		if ( ! zz_start_stack )
			zz_start_stack = (int *) zz_flex_alloc( new_size );

		else
			zz_start_stack = (int *) zz_flex_realloc(
					(void *) zz_start_stack, new_size );

		if ( ! zz_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	zz_start_stack[zz_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void zz_pop_state()
	{
	if ( --zz_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(zz_start_stack[zz_start_stack_ptr]);
	}


static int zz_top_state()
	{
	return zz_start_stack[zz_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void zz_fatal_error( const char msg[] )
#else
static void zz_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine zzless() so it works in section 3 code. */

#undef zzless
#define zzless(n) \
	do \
		{ \
		/* Undo effects of setting up zztext. */ \
		zztext[zzleng] = zz_hold_char; \
		zz_c_buf_p = zztext + n - YY_MORE_ADJ; \
		zz_hold_char = *zz_c_buf_p; \
		*zz_c_buf_p = '\0'; \
		zzleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef zztext_ptr
#ifdef YY_USE_PROTOS
static void zz_flex_strcpy( char *s1, const char *s2 )
#else
static void zz_flex_strcpy( s1, s2 )
char *s1;
const char *s2;
#endif
	{
	while ( (*(s1++) = *(s2++)) )
		;
	}
#endif


#ifdef YY_USE_PROTOS
static void *zz_flex_alloc( unsigned int size )
#else
static void *zz_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *zz_flex_realloc( void *ptr, unsigned int size )
#else
static void *zz_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void zz_flex_free( void *ptr )
#else
static void zz_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 144 "../chop/cmd.lex"


